\c userregistration;

-- Inserta nuevos registros en la tabla 'states'
INSERT INTO countries (id, name)
VALUES
('AD','Andorra'),
('AE','Emiratos Arabes Unidos'),
('AF','Afganistan'),
('AG','Antigua y Barbuda'),
('AI','Anguila'),
('AL','Albania'),
('AM','Armenia'),
('AN','Antillas Holandesas'),
('AO','Angola'),
('AQ','Antartida'),
('AR','Argentina'),
('ASM','Samoa Americana'),
('AU','Austria'),
('AUS','Australia'),
('AW','Aruba'),
('AZ','Azerbaiyan'),
('BA','Bosnia y Herzegovina'),
('BB','Barbados'),
('BD','Bangladesh'),
('BE','Beligica'),
('BF','Burkina Faso'),
('BH','Bahrein'),
('BI','Burundi'),
('BJ','Benin'),
('BM','Bermudas'),
('BO','Bolivia'),
('BR','Brasil'),
('BS','Bahamas'),
('BT','Butan'),
('BU','Isla Bouvet'),
('BV','Bulgaria'),
('BW','Botswana'),
('BX','Brunei Darussalam'),
('BY','Bielorrusia'),
('BZ','Belice'),
('CA','Canada'),
('CC','Cocos (Keeling)'),
('CF','Republica Centroafricana'),
('CG','Congo'),
('CH','Suiza'),
('CI','Cote D''Ivoire (Costa de Marfil)'),
('CK','Islas Cook'),
('CL','Chile'),
('CM','Camerun'),
('CN','China'),
('CO','Colombia'),
('CR','Costa Rica'),
('CU','Cuba'),
('CV','Cabo Verde'),
('CX','Isla de Navidad'),
('CY','Chipre'),
('CZ','Republica Checa'),
('DE','Alemania'),
('DJ','Djibouti'),
('DK','Dinamarca'),
('DM','Dominica'),
('DO','Republica Dominicana'),
('DZ','Argelia'),
('EC','Ecuador'),
('EE','Estonia'),
('EG','Egipto'),
('EH','Sahara Occidental'),
('ER','Eritrea'),
('ES','Espana'),
('ET','Etiopia'),
('FI','Finlandia'),
('FJ','Fiji'),
('FK','Islas Malvinas (Falkland)'),
('FM','Micronesia'),
('FO','Islas Feroe'),
('FR','Francia'),
('GA','Gabon'),
('GB','Gran Bretana (Reino Unido)'),
('GD','Granada'),
('GE','Georgia'),
('GF','Guyana Francesa'),
('GH','Ghana'),
('GI','Gibraltar'),
('GL','Groenlandia'),
('GM','Gambia'),
('GN','Guinea'),
('GP','Guadalupe'),
('GQ','Guinea Ecuatorial'),
('GR','Grecia'),
('GS','Georgia del Sur y Islas Sandwich del Sur'),
('GT','Guatemala'),
('GU','Guam'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HK','Hong Kong'),
('HM','Islas Heard y McDonald'),
('HN','Honduras'),
('HR','Croacia'),
('HT','Haiti'),
('HU','Hungria'),
('ID','Indonesia'),
('IE','Irlanda'),
('IL','Israel'),
('IN','India'),
('IO','Territorio Britanico del Oceano Indico'),
('IQ','Irak'),
('IR','Iran'),
('IS','Islandia'),
('IT','Italia'),
('JM','Jamaica'),
('JO','Jordania'),
('JP','Japon'),
('KE','Kenia'),
('KG','Kirguistan'),
('KH','Camboya'),
('KI','Kiribati'),
('KM','Comoras'),
('KN','Saint Kitts y Nevis'),
('KP','Corea del Norte'),
('KR','Corea del Sur'),
('KW','Kuwait'),
('KY','Las Islas Caiman'),
('KZ','Kazajstan'),
('LA','Laos'),
('LB','Libano'),
('LC','Santa Lucia'),
('LI','Liechtenstein'),
('LK','Sri Lanka'),
('LR','Liberia'),
('LS','Lesoto'),
('LT','Lituania'),
('LU','Luxemburgo'),
('LV','Letonia'),
('LY','Libia'),
('MA','Marruecos'),
('MC','Monaco'),
('MD','Moldavia'),
('MG','Madagascar'),
('MH','Islas Marshall'),
('MK','Macedonia'),
('ML','Mali'),
('MM','Myanmar'),
('MN','Mongolia'),
('MO','Macao'),
('MP','Islas Marianas del Norte'),
('MQ','Martinica'),
('MR','Mauritania'),
('MS','Montserrat'),
('MT','Malta'),
('MU','Mauricio'),
('MV','Maldivas'),
('MW','Malawi'),
('MX','Mexico'),
('MY','Malasia'),
('MZ','Mozambique'),
('NAM','Namibia'),
('NC','Nueva Caledonia'),
('NE','Niger'),
('NF','Norfolk Island'),
('NG','Nigeria'),
('NI','Nicaragua'),
('NLD','Paises Bajos'),
('NO','Noruega'),
('NP','Nepal'),
('NR','Nauru'),
('NU','Niue'),
('NZ','Nueva Zelanda'),
('OM','Oman'),
('PA','Panama'),
('PE','Peru'),
('PF','Polinesia Frances'),
('PG','Papua Nueva Guinea'),
('PH','Filipinas'),
('PK','Pakistan'),
('PO','Polonia'),
('PM','San Pedro y Miquelon'),
('PN','Pitcairn'),
('PR','Puerto Rico'),
('PT','Portugal'),
('PW','Palau'),
('PY','Paraguay'),
('QA','Qatar'),
('RE','Reunion'),
('RO','Rumania'),
('RU','La Federacion de Rusia'),
('RW','Ruanda'),
('SA','Arabia Saudita'),
('SB','Las Islas Salomon'),
('SC','Seychelles'),
('SD','Sudan'),
('SE','Suecia'),
('SG','Singapur'),
('SH','Santa Elena'),
('SI','Eslovenia'),
('SJ','Svalbard y Jan Mayen'),
('SK','Republica Eslovaca'),
('SL','Sierra Leona'),
('SM','San Marino'),
('SN','Senegal'),
('SO','Somalia'),
('SR','Suriname'),
('ST','Santo Tome y Principe'),
('SV','El Salvador'),
('SY','Siria'),
('SZ','Swazilandia'),
('TC','Islas Turcas y Caicos'),
('TD','Chad'),
('TF','Territorios del sur frances'),
('TG','Togo'),
('TH','Tailandia'),
('TI','Tayikistan'),
('TK','Tokelau'),
('TM','Turkmenistan'),
('TN','Tunez'),
('TO','Tonga'),
('TP','Timor Oriental'),
('TR','Turquia'),
('TT','Trinidad y Tobago'),
('TV','Tuvalu'),
('TW','Taiwan'),
('TZ','Tanzania'),
('UA','Ucrania'),
('UG','Uganda'),
('UK','Reino Unido'),
('UM','Islas menores de EE.UU.'),
('US','Estados Unidos de America (EE.UU.)'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VA','Ciudad del Vaticano'),
('VC','San Vicente y las Granadinas'),
('VE','Venezuela'),
('VG','Islas Virgenes (Britanicas)'),
('VN','Vietnam'),
('VU','Vanuatu'),
('WF','Islas Wallis y Futuna'),
('WS','Samoa'),
('YE','Yemen'),
('YT','Mayotte'),
('YU','Yugoslavia'),
('ZA','Sudafrica'),
('ZM','Zambia'),
('ZR','Zaire'),
('ZW','Zimbabue')
ON CONFLICT (id) DO NOTHING;